service: platform-racing

package:
  exclude:
    - "node_modules/.bin"

custom:
  bucket: pr4-levels

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/pr2/*"

functions:
  import-level:
    handler: src/index.handler
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 30 # optional, in seconds, default is 6
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - http:
          path: import-from-pr2/{levelId}
          method: get
          request:
            parameters:
               paths:
                 levelId: true
